---
title: "Linear SDR for multivariate Y"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Linear SDR for multivariate Y}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2)
library(linearsdr)
data('energy_datta', package="linearsdr")
summary(energy_datta)
dim(energy_datta)

X = as.matrix(energy_datta[,1:8])
Y1 = as.numeric(energy_datta$Y1)
Y2 = as.numeric(energy_datta$Y2)

pairs(X)
```

```{r}

b_hat_sir = sir(x=X, y=Y1, nslices = 10, d=2, ytype = "continuous" )$beta


linearsdr:::ggplot_fsdr(Y1, t((X)%*%b_hat_sir[,1:2]), y_on_axis=F,
                        ytype="continuous",
                        h_lab='SIR 1', v_lab='SIR 2',
                        main_lab= paste0('SIR'), size=3)


```


```{r}

b_hat_dr = dr(x=X, y=Y1, nslices = 10, d=2, ytype = "continuous" )$beta

linearsdr:::ggplot_fsdr(Y2, t((X)%*%b_hat_dr[,1]), y_on_axis=T,
                        ytype="continuous",
                        h_lab='DR 1', v_lab='DR 2',
                        main_lab= paste0('DR'), size=3)




```

Forward methods using OPG
```{r}
# Parallelization not run because of computational time. 

# library("doParallel")
# library("foreach")
# print( paste( as.character(detectCores()), "cores detected" ) );
# # Create cluster with desired number of cores
# if ( !grepl("hxq5", getwd()) ) {
#   cl <- makePSOCKcluster(detectCores()-1)
# } else if ( grepl("hxq5", getwd()) ) {
#   cl <- parallel::makeCluster(nprocs, type=mp_type)
# }
# # Register cluster
# doParallel::registerDoParallel(cl)
# # Find out how many cores are being used
# print( paste( as.character(getDoParWorkers() ), "cores registered" ) )
# # stopCluster(cl)

X_std=(sapply(1:dim(X)[2], FUN= function(j)
  center_cpp(X[,j], NULL) ) )%*%matpower_cpp(cov((X)) , -1/2);
# X_std = sapply(1:dim(X)[2], FUN= function(j) center_cpp(X[,j], NULL)/sd(X[,j]) ) ;

b_hat_opg = opcg(x=X_std, y=Y1, bw = 5, d=2, ytype = "continuous", 
                 method= "cg", parallelize = F )


linearsdr:::ggplot_fsdr(Y1, t((X_std)%*%b_hat_opg[,1:2]), y_on_axis=F,
                        ytype="continuous",
                        h_lab='OPG 1', v_lab='OPG 2',
                        main_lab= paste0('OPG'), size=3)

```
