---
title: "Linear SDR for scalar Y, Ex1"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Linear SDR for scalar Y, Ex1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2)
library(linearsdr)
data('airfoil_datta', package="linearsdr")
# summary(airfoil_datta)

X = as.matrix(airfoil_datta[,1:5])
Y = c(airfoil_datta[,6])

pairs(X)
```

```{r}
# Sliced Inverse Regression

b_hat_sir = sir(x=X, y=Y, nslices = 5, d=2, ytype = "continuous" )$beta


linearsdr:::ggplot_fsdr(Y, t((X)%*%b_hat_sir[,1]), y_on_axis=T,
                        ytype="continuous",
                        h_lab='SIR 1', v_lab='Y',
                        main_lab= paste0('SIR'), size=2.5)

```
```{r}
# Sliced Average Variance Estimator

b_hat_save = save_sdr(x=X, y=Y, nslices = 5, d=2, ytype = "continuous" )$beta


linearsdr:::ggplot_fsdr(Y, t((X)%*%b_hat_save[,1]), y_on_axis=T, 
                        ytype="continuous",
                        h_lab='DR 1', v_lab='Y',
                        main_lab= paste0('DR'), size=2.5)




```

```{r}
# Directional Regression

b_hat_dr = dr(x=X, y=Y, nslices = 5, d=2, ytype = "continuous" )$beta


linearsdr:::ggplot_fsdr(Y, t((X)%*%b_hat_dr[,1]), y_on_axis=T, 
                        ytype="continuous",
                        h_lab='DR 1', v_lab='Y',
                        main_lab= paste0('DR'), size=2.5)




```

Forward methods using OPG
```{r}
# OPG Estimate 

library("doParallel")
library("foreach")
print( paste( as.character(detectCores()), "cores detected" ) );
# Create cluster with desired number of cores
if ( !grepl("hxq5", getwd()) ) {
  cl <- makePSOCKcluster(detectCores()-1)
} else if ( grepl("hxq5", getwd()) ) {
  cl <- parallel::makeCluster(nprocs, type=mp_type)
}
# Register cluster
doParallel::registerDoParallel(cl)
# Find out how many cores are being used
print( paste( as.character(getDoParWorkers() ), "cores registered" ) )
# stopCluster(cl)

X_std=(sapply(1:dim(X)[2], FUN= function(j)
  center_cpp(X[,j], NULL) ) )%*%matpower_cpp(cov((X)) , -1/2);


b_hat_opg = opcg(x=X_std, y=Y, bw = 5, d=2, ytype = "continuous", 
                 method= "cg", parallelize = T )


linearsdr:::ggplot_fsdr(Y, t((X_std)%*%b_hat_opg[,1]), y_on_axis=T,
                        ytype="continuous",
                        h_lab='OPG 1', v_lab='Y',
                        main_lab= paste0('OPG'), size=2.5)

```

```{r}
# MAVE Estimate
n=length(Y)
b_hat_made = made(x=(X_std), matrix(Y, nrow = n, ncol=1), bw=5, d=2,
                  ytype='continuous',
                  method=list(opcg="cg", made="cg"), B_mat = NULL,
                  parallelize=T,
                  control_list=list(print_iter=T, max_iter_made=5) )

 
linearsdr:::ggplot_fsdr(Y, t((X_std)%*%b_hat_made[,1]), y_on_axis=T,
                        ytype="continuous",
                        h_lab='MADE 1', v_lab='Y',
                        main_lab= paste0('MADE'), size=2.5)

```